api_provider:
  default: "giphy"
  type: "enum"
  description:
    en: "Which gifs provider should we use"
  choices:
    - giphy
    - tenor
giphy_api_key:
  type: string
  default: ""
  description:
    en: "GIPHY API key"
tenor_api_key:
  type: string
  default: ""
  description:
    en: "TENOR API key"
tenor_client_key:
  type: string
  default: "Discourse"
  description:
    en: "TENOR - client-specified string that represents the integration"
giphy_locale:
  type: enum
  default: en
  description:
    en: "Language to use on the search. Used to cater search to regional content. Set to your default forum locale."
  choices:
    - ar
    - bn
    - cs
    - da
    - de
    - en
    - es
    - fa
    - fi
    - fr
    - hi
    - hu
    - id
    - it
    - iw
    - ja
    - ko
    - ms
    - nl
    - no
    - pl
    - pt
    - ro
    - ru
    - sv
    - th
    - tl
    - tr
    - uk
    - vi
    - zh-CN
    - zh-TW
giphy_file_format:
  type: enum
  default: webp
  description:
    en: "GIPHY: Image format to use. WEBP has smaller files that load quicker while GIF provides compatibility with old browsers."
  choices:
    - webp
    - gif
tenor_file_detail:
  type: enum
  default: webp_transparent
  description:
    en: "TENOR: Image format to use. WEBP has smaller files that load quicker while GIF provides compatibility with old browsers."
  choices:
    - gif
    - mediumgif
    - tinygif
    - nanogif
    - gif_transparent
    - tinygif_transparent
    - nanogif_transparent
    - webp_transparent
    - tinywebp_transparent
    - nanowebp_transparent
    - mp4
    - loopedmp4
    - tinymp4
    - webm
    - tinywebm
    - nanowebm
giphy_content_rating:
  type: enum
  default: r
  description:
    en: 'GIPHY: Content rating for search results, more info at <a href="https://developers.giphy.com/docs/optional-settings#rating">https://developers.giphy.com/docs/optional-settings#rating</a>.'
  choices:
    - g
    - pg
    - pg-13
    - r
tenor_content_filter:
  type: "enum"
  default: high
  description:
    en: "TENOR: Content safety level for Tenor results"
  choices:
    - high
    - medium
    - low
    - "off"
