api_provider:
  default: "giphy"
  type: "enum"
  choices:
    - giphy
    - tenor
    - klipy
giphy_api_key:
  type: string
  default: ""
giphy_file_format:
  type: enum
  default: webp
  choices:
    - webp
    - gif
giphy_size_variant:
  type: enum
  default: downsized_medium
  choices:
    - original
    - downsized_large
    - downsized_medium
    - downsized
giphy_content_rating:
  type: enum
  default: r
  choices:
    - g
    - pg
    - pg-13
    - r
giphy_locale:
  type: enum
  default: en
  choices:
    - ar
    - bn
    - cs
    - da
    - de
    - en
    - es
    - fa
    - fi
    - fr
    - hi
    - hu
    - id
    - it
    - iw
    - ja
    - ko
    - ms
    - nl
    - no
    - pl
    - pt
    - ro
    - ru
    - sv
    - th
    - tl
    - tr
    - uk
    - vi
    - zh-CN
    - zh-TW
limit_infinite_search_results:
  type: bool
  default: false
max_results_limit:
  type: integer
  min: 24
  default: 240
tenor_api_key:
  type: string
  default: ""
tenor_client_key:
  type: string
  default: "discourse"
tenor_file_detail:
  type: enum
  default: mediumgif
  choices:
    - gif
    - mediumgif
    - tinygif
    - nanogif
tenor_content_filter:
  type: "enum"
  default: high
  choices:
    - high
    - medium
    - low
    - "off"
tenor_country:
  type: string
  default: "US"
tenor_locale:
  type: string
  default: "en_US"
klipy_api_key:
  type: string
  default: ""
klipy_file_detail:
  type: enum
  default: webp
  choices:
    - webp
    - gif
klipy_content_filter:
  type: "enum"
  default: high
  choices:
    - high
    - medium
    - low
    - "off"
klipy_country:
  type: string
  default: "US"
klipy_locale:
  type: string
  default: "en_US"
